#!/usr/bin/env python3
"""Executable shim for the skill-feedback package."""

import sys

from skill_feedback.commands import main


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
